cabal-version:      3.0
name:               worklog
version:            0.2.0.2
synopsis:           Simple workfile management application
description:        Manages work files. Creates summary, filter, change attributes and run the application which handles the workfiles. Use simple project framework with additional files related to the workfile.
license:            BSD-3-Clause
license-file:       LICENSE
author:             Somogyi András
maintainer:         somogyiandras74@gmail.com
-- copyright:
category:           work managment
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:
source-repository head
  type:     git
  location: git//github.com/somogyiandras/worklog.git

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  
                      Worklog.Task
                    , Worklog.TaskAnalysis
    -- other-modules:
    -- other-extensions:
    build-depends:    base ^>=4.21.0.0
                    , time < 1.16.0.1
                    , containers < 0.8
    hs-source-dirs:   src
    default-language: GHC2021

executable worklog
    import:           warnings
    main-is:          Main.hs
    -- other-modules:
    -- other-extensions:
    build-depends:
                      base ^>=4.21.0.0
                    , worklog
                    , time < 1.16.0.1
    hs-source-dirs:   app
    default-language: GHC2021

test-suite worklog-test
    import:           warnings
    default-language: GHC2021
    other-modules:
                      Worklog.TaskSpec
    -- other-extensions:
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:
                      base ^>=4.21.0.0
                    , worklog
                    , tasty
                    , tasty-hunit
