name: Haskell CI on windows

on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.12'
          cabal-version: '3.12'

      - name: Build
        run: cabal build all

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: Main
          path: D:\\a\\worklog\\worklog\\dist-newstyle\\build\\x86_64-windows\\ghc-9.12.4\\worklog-0.2.0.2\\x\\worklog\\build\\worklog\\worklog.exe
          retention-days: 20
