name: Haskell CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.12'
          cabal-version: '3.12'

      - name: Build
        run: cabal build all

      - name: Test
        run: cabal test all
